MESH-1638/Add a reverse map to allow an easy lookup from IdentityId to list of assets for which the identity is an EA
PolymathNetwork/Polymesh pull request #1021
Opened 2021-06-09 06:06 UTC by CJP10

## changelog

### new features

- External agents now has a mapping for Agents to what tickers they are agents for.

2021-06-09 10:58 UTC, Centril commented on pallets/external-agents/src/lib.rs
>              match (*slot, group) {
The old structure was simpler. I'd prefer adding another `if group.is_none() { AgentOf::remove(...) }` below the `try_mutate`, keeping the current `match` untouched, and purely handling addition in `unchecked_add_agent`.

2021-06-09 10:58 UTC, Centril requested changes

2021-06-09 10:58 UTC, Centril commented on pallets/external-agents/src/lib.rs
> +                => Vec<Ticker>;
You're introducing an unbounded-ness attack vector into EAs here. Let's use a double map instead.

2021-06-11 10:49 UTC, Centril requested changes

2021-06-11 10:49 UTC, Centril commented on pallets/runtime/tests/src/external_agents_test.rs
> +}
So `create_asset` already exists in `asset_test`; let's import that one instead.

2021-06-11 10:49 UTC, Centril commented on pallets/runtime/tests/src/external_agents_test.rs
> +                Id::add_auth(from.did, sig, data, None)
Let's dedup the `add_auth` part with the one in `fn add_works` into a top level function, e.g., `fn add_become_agent(...)`.

2021-06-11 10:49 UTC, Centril commented on pallets/runtime/tests/src/external_agents_test.rs
> +            .into_iter()
```suggestion
```
Ranges are already iterators.

2021-06-11 10:49 UTC, Centril commented on pallets/runtime/tests/src/external_agents_test.rs
> +fn agent_of_mapping_works() {
This test needs more commentary overall, as in the tests above.

2021-06-11 10:49 UTC, Centril commented on pallets/runtime/tests/src/external_agents_test.rs
> +            agents.sort();
You can also test this against `GroupOfAgent::iter().filter(|(_, d, _)| d == user.did).map(|(t, ..)| t).collect()` and ensure consistency, which is really the crucial property.

2021-06-11 10:49 UTC, Centril commented on pallets/external-agents/src/lib.rs
> +                }
This could just be `if group.is_none() { AgentOf::remove(agent, ticker); }` just before the `Ok(())` and then the `match` can be left untouched.

2021-06-14 08:08 UTC, Centril commented on pallets/external-agents/src/lib.rs
> +            if slot.is_none() {
```suggestion
            if group.is_none() {
```

2021-06-14 08:08 UTC, Centril commented on pallets/runtime/tests/src/external_agents_test.rs
> +    ));
What I was asking for is to dedup the creation of the auth itself, not the accepting bit, so that the `add` closure below gets simplified too.

2021-06-16 08:13 UTC, Centril approved these changes

2021-06-16 12:37 UTC, adamdossa approved these changes

2021-06-16 12:38 UTC, adamdossa commented
@CJP10 approved from my end, but please could you add details of the reverse map "API" to the change log to make it easier for upstream teams to leverage?

2021-06-16 13:37 UTC, merged