MESH-1654/ Simple Relayer Integration Test
PolymathNetwork/Polymesh pull request #1082
Opened 2021-08-20 18:34 UTC by JMoore96

Created integration test for relayer module.

2021-08-23 13:15 UTC, Neopallium requested changes

2021-08-25 15:18 UTC, Neopallium commented on scripts/cli/src/helpers/relayer_helper.ts
> +}
Please also add some test-cases that should fail.

2021-08-30 13:42 UTC, Neopallium approved these changes

2021-08-31 10:04 UTC, adamdossa approved these changes

2021-09-02 03:41 UTC, CJP10 approved these changes

2021-09-02 09:44 UTC, merged