MESH-1747 Added checks to secondary key limits
PolymathNetwork/Polymesh pull request #1160
Opened 2021-11-22 14:56 UTC by raycar5

fixed make_multisig_signer and join_identity

2021-11-22 15:08 UTC, Neopallium commented on pallets/identity/src/keys.rs
>              Self::ensure_key_did_unlinked(&key)?;
I think it would be useful to pull these two checks into one function `ensure_add_secondary_key(did, key)`.

2021-11-22 15:11 UTC, Neopallium commented on pallets/multisig/src/lib.rs
> +
I would move this check up by the `ensure_key_did_unlinked`.  Doing the checks as early as possible helps to decrease the cost to the node for bad requests.  Here it is not saving much, but would be nice anyways.

2021-11-22 17:22 UTC, Neopallium requested changes
Looks good other then the extra dep.

2021-11-22 17:22 UTC, Neopallium commented on pallets/multisig/Cargo.toml
> +pallet-base = { path = "../base", default-features = false }
No longer needed.  Same with the `Cargo.lock` change.

2021-11-22 20:09 UTC, Neopallium approved these changes

2021-11-23 13:01 UTC, Centril approved these changes

2021-11-23 13:50 UTC, CJP10 approved these changes

2021-11-29 14:57 UTC, adamdossa approved these changes

2021-11-29 16:02 UTC, merged