MESH-1746 fix scope with disabled investor uniqueness
PolymathNetwork/Polymesh pull request #1162
Opened 2021-11-23 12:54 UTC by Neopallium

Minting of new tokens wasn't updating the scope balance for the issuer if Investor Uniqueness was disabled.

## changelog

### modified logic

- `identity.issue` - Now always updates the scope balance.

2021-11-23 15:00 UTC, Centril requested changes

2021-11-23 15:05 UTC, Neopallium commented on pallets/runtime/tests/src/statistics_test.rs
> +    // Total supply over the limit.
Ah.  That was an old comment from before.  I will fix it.

2021-11-23 15:58 UTC, Centril approved these changes

2021-11-24 19:46 UTC, CJP10 approved these changes

2021-11-29 14:57 UTC, adamdossa approved these changes

2021-11-29 14:57 UTC, merged