MESH-1759 Remove porfolio name to number mapping after deletion
PolymathNetwork/Polymesh pull request #1200
Opened 2022-01-17 12:10 UTC by raycar5

## changelog

### modified logic

The portfolio name is now removed from the NameToNumber mapping in the `delete_portfolio` extrinsic.

2022-01-17 12:31 UTC, Centril approved these changes

2022-01-19 02:48 UTC, CJP10 approved these changes

2022-01-19 16:10 UTC, Neopallium requested changes
This should have a storage migration to cleanup deleted portfolio.

2022-01-21 12:08 UTC, Centril approved these changes
Logic looks good, this just simplifies + formats code a bit.

2022-01-21 12:08 UTC, Centril commented on pallets/portfolio/src/lib.rs
> +                }
```suggestion
                NameToNumber::iter()
                    .filter(|(identity, name, number)| !Portfolios::contains_key(identity, number))
                    .for_each(|(identity, name, _)| NameToNumber::remove(identity, name));
```

2022-01-21 12:08 UTC, Centril commented on pallets/portfolio/src/lib.rs
> +            use polymesh_primitives::{ storage_migrate_on };
```suggestion
            use polymesh_primitives::storage_migrate_on;
```

2022-01-21 12:08 UTC, Centril commented on pallets/portfolio/src/lib.rs
> +            let portfolio =Portfolios::get(&primary_did,&num);
```suggestion
            let portfolio = Portfolios::get(&primary_did, &num);
```

2022-01-21 13:18 UTC, Centril commented on pallets/portfolio/src/lib.rs
> +                    .filter(|(identity, name, number)| !Portfolios::contains_key(identity, number))
```suggestion
                    .filter(|(identity, _, number)| !Portfolios::contains_key(identity, number))
```

2022-01-24 10:52 UTC, Neopallium approved these changes

2022-01-25 14:33 UTC, merged