Mesh 1792/ improving signer already linked errors
PolymathNetwork/Polymesh pull request #1226
Opened 2022-03-17 12:44 UTC by JMoore96

## changelog

### modified logic

- Created more specific error types for improving singer already linked type errors

2022-03-17 13:10 UTC, Centril commented on pallets/multisig/src/lib.rs
> +        /// Signer is an account key that is already associated with a identity.
```suggestion
        /// Signer is an account key that is already associated with an identity.
```

2022-03-17 14:31 UTC, Centril approved these changes

2022-03-17 15:30 UTC, Neopallium requested changes

2022-03-17 15:30 UTC, Neopallium commented on pallets/multisig/src/lib.rs
> +                ensure!(key != &multisig, Error::<T>::SignerAlreadyLinkedToMultisig);
Lets use a different error for this one.  Since these are three different failure cases, it is easier for the user to know why it failed.

2022-03-17 15:30 UTC, Neopallium commented on pallets/runtime/tests/src/multisig.rs
> +            Error::SignerAlreadyLinkedToMultisig
If there was only one test for the old error, then we haven't been testing all three failure cases.

Please add a test case for the other two failure cases.

2022-03-25 15:01 UTC, Neopallium commented
Task for the tests: MESH-1803

2022-03-25 15:04 UTC, Neopallium commented
Approved for now, so we can merge it.

2022-03-25 15:53 UTC, Neopallium commented
The title change was to fix the stuck `WIP` status check.

2022-03-25 15:53 UTC, merged