[WIP] MESH-1803/ Add missing tests for MESH-1792 & MESH-1767
PolymathNetwork/Polymesh pull request #1227
Opened 2022-03-29 20:01 UTC by JMoore96

## changelog

### modified logic

- adding tests for checking multisig errors and secondary key & permission limits

2022-03-30 08:54 UTC, Neopallium requested changes
Minor comment changes.  Otherwise looks good to me.

2022-03-30 08:54 UTC, Neopallium commented on pallets/runtime/tests/src/multisig.rs
> +        );
Please add some comments to describe what is being tested.

2022-03-30 08:54 UTC, Neopallium commented on pallets/multisig/src/lib.rs
> +        MultisigNotAllowedToLinkToItself,
```suggestion
        /// Multisig not allowed to add itself as a signer.
        MultisigNotAllowedToLinkToItself,
```

2022-03-30 10:44 UTC, Neopallium commented
Also missing the tests for MESH-1767.

2022-04-12 19:21 UTC, JMoore96 commented on pallets/runtime/tests/src/identity_test.rs
> +fn ensure_perms_limited() {
just finished making the change.

2022-04-13 13:20 UTC, Neopallium reviewed
The test for `Identity::cdd_register_did` looks good.  But we are still missing tests for the new errors from the MESH-1792 PR.  See the comment here: https://github.com/PolymathNetwork/Polymesh/pull/1226#discussion_r829192129

EDIT: Sorry, this is already done.  This PR looks good.

2022-04-13 14:47 UTC, Neopallium approved these changes

2022-04-17 17:00 UTC, CJP10 approved these changes

2022-04-18 11:07 UTC, merged