MESH-1824: Empty perms default + MESH-1825: Contracts RPC
PolymathNetwork/Polymesh pull request #1239
Opened 2022-05-08 15:54 UTC by Centril

## changelog

### modified API

- Contracts `instantiate` APIs now use empty permissions by default.
- Enable RPC for contracts.

2022-05-12 13:49 UTC, Neopallium commented on pallets/runtime/common/src/runtime.rs
> +                    Contracts::bare_instantiate(origin, endowment, gas_limit, code, data, salt, false)
I think this RPC endpoint needs the logic from our contract pallet's `instantiate_with_code`, (i.e. attach the contract address to the caller's identity).

2022-05-12 15:05 UTC, Neopallium commented on pallets/runtime/common/src/runtime.rs
> +                    Contracts::bare_instantiate(origin, endowment, gas_limit, code, data, salt, false)
I think these RPC endpoints are only for testing if an instantiate/call will work (i.e. dry-run).  It should be fine to use the `instantiate` call without permissions.  We just want this interface to be as compatible with the Contracts UI as possible.

2022-05-12 23:10 UTC, CJP10 approved these changes

2022-05-16 10:38 UTC, Neopallium requested changes
Looks good.  Just a minor comment change.

2022-05-16 10:38 UTC, Neopallium commented on pallets/contracts/src/lib.rs
> +            Self::prepare_instantiate(did, &sender, &code_hash, &salt, Permissions::empty())?;
There is no transaction here.  No `Roll back`.

2022-05-16 13:32 UTC, adamdossa approved these changes

2022-05-16 13:32 UTC, merged