MESH-1808/ Add missing asset info in AssetCreated event
PolymathNetwork/Polymesh pull request #1272
Opened 2022-06-29 18:05 UTC by JMoore96

## changelog

### modified API

- add a few new fields to `AssetCreated` event

2022-06-29 19:17 UTC, Neopallium requested changes

2022-06-29 19:17 UTC, Neopallium commented on pallets/asset/src/lib.rs
> +        AssetNames::insert(&ticker, name.clone());
```suggestion
        AssetNames::insert(&ticker, &name);
```
It should be possible to avoid cloning here.  The `insert` method can take a reference or value here, it just needs to encode the value and not take ownership.

For a normal Rust `HashMap` or other container type, this wouldn't be possible.  But Substrate storage types don't really hold the value, then encode it to raw bytes before writing it to the storage backend.

2022-06-29 19:46 UTC, JMoore96 commented on pallets/asset/src/lib.rs
> +        AssetNames::insert(&ticker, name.clone());
just made the change.

2022-06-29 21:04 UTC, Neopallium approved these changes
Looks good.

2022-06-30 13:29 UTC, adamdossa approved these changes

2022-07-04 16:28 UTC, CJP10 approved these changes

2022-07-12 13:47 UTC, merged