[WIP] MESH-1853/ add field for external id to settlements
PolymathNetwork/Polymesh pull request #1280
Opened 2022-07-19 17:42 UTC by JMoore96

## changelog

### modified API

- added Instruction with memo 
- updated storage and events

2022-07-20 13:13 UTC, Neopallium commented on pallets/settlement/src/lib.rs
> +        ),
Lets just have this event contain the following field:

1. did
2. venue id
3. instruction id
4. memo: InstructionMemo // No `Option` needed here.

Then only emit this event when there is a memo (i.e. memo is some).

2022-07-20 13:13 UTC, Neopallium commented on pallets/settlement/src/lib.rs
> +    pub instruction_memo: Option<InstructionMemo>,
This field isn't needed, since the memos are stored in a separate storage map.  Adding this field  would require doing a migration.

2022-07-21 11:30 UTC, Neopallium commented on pallets/settlement/src/lib.rs
> +            Self::base_add_instruction(did, venue_id, settlement_type, trade_date, value_date, legs, instruction_memo)?;
Don't add the `memo` parameter to the existing extrinsics `add_instruction` and `add_and_affirm_instruction`.  These extrinsics will just pass `None` to `base_add_instruction` for the memo.  Create a new extrinsic `add_instruction_with_memo` to provide the memo.

2022-07-21 11:30 UTC, Neopallium commented on pallets/settlement/src/lib.rs
> +                let instruction_id = Self::base_add_instruction(did, venue_id, settlement_type, trade_date, value_date, legs, instruction_memo)?;
Same here.  Just pass `None` for the memo to `base_add_instruction`.

2022-07-22 09:01 UTC, Neopallium commented on pallets/settlement/src/lib.rs
> +        /// * `memo` - Optional memo field for this instruction.
This extrinsic doesn't have the `memo` parameter anymore.  So this needs to be removed.

2022-07-22 09:04 UTC, Neopallium commented on pallets/settlement/src/lib.rs
> +            ));
Let's just keep the `InstructionCreated` event and add the `Memo` to that event.

2022-07-27 14:46 UTC, Neopallium requested changes
Once the memo is changed to a fixed-length array, this PR  should be finished.

2022-07-27 14:46 UTC, Neopallium commented on pallets/settlement/src/lib.rs
> +pub struct InstructionMemo(Vec<u8>);
Based on what we discussed in the stand-up.  Change the memo from a `Vec` to fixed length array:
```suggestion
pub struct InstructionMemo(pub [u8; 32]);
```

2022-07-28 13:50 UTC, adamdossa commented
- We should add a `with_memo` version of `add_and_affirm_instruction`
- We can mark the old `add_instruction` and `add_and_affirm_instruction` as deprecated

2022-08-01 12:32 UTC, Neopallium requested changes

2022-08-01 12:32 UTC, Neopallium commented on pallets/settlement/src/lib.rs
> +            instruction_memo: InstructionMemo,
This should be `Option<InstructionMemo>`, because it will replace the non-memo extrinsic.

2022-08-01 12:32 UTC, Neopallium commented on pallets/settlement/src/lib.rs
> +            instruction_memo: InstructionMemo,
Same here.

2022-08-04 13:28 UTC, Neopallium approved these changes

2022-08-04 13:40 UTC, adamdossa approved these changes

2022-08-04 13:40 UTC, merged