MESH-1800/ changed multiSig.MultiSigSigners map to bool
PolymathNetwork/Polymesh pull request #1282
Opened 2022-07-26 02:29 UTC by JMoore96

## changelog

### modified logic

- modified MultiSigSigners map

2022-07-27 12:10 UTC, Neopallium requested changes
Needs a storage migration.

2022-07-28 13:54 UTC, adamdossa commented
Ideally we should use `get` instead of `contains_key` in e.g.:
`!<MultiSigSigners<T>>::contains_key(&multisig, &signer),`
to check that the key maps to false (rather than just being absent).

2022-07-29 18:13 UTC, Neopallium requested changes
One minor change and it is ready.

2022-07-29 18:13 UTC, Neopallium commented on pallets/multisig/src/lib.rs
> +                <MultiSigSigners<T>>::insert(&signer, &ms, true);
The parameter names are backwards.  The `ms` is the first key in the double map and `signer` is the second key.

2022-08-01 12:39 UTC, Neopallium approved these changes

2022-08-02 13:39 UTC, adamdossa approved these changes

2022-08-02 13:39 UTC, merged