MESH-1823/ don't allow settlement with zero amount
PolymathNetwork/Polymesh pull request #1284
Opened 2022-07-27 16:55 UTC by JMoore96

## changelog

### modified logic

- check instruction leg amount and returns error if zero
- add test
- remove tests with instruction leg amount being zero

2022-07-28 10:54 UTC, Neopallium requested changes

2022-07-28 10:54 UTC, Neopallium commented on pallets/runtime/tests/src/settlement_test.rs
> -                },
We can keep this test and just remove this one leg.

2022-07-28 12:00 UTC, adamdossa commented on pallets/settlement/src/lib.rs
> +        InsufficientAmount,
Could we change to `ZeroAmount` as I think that will be a bit clearer as to what the issue is.

2022-08-04 13:23 UTC, Neopallium approved these changes

2022-08-04 13:41 UTC, adamdossa approved these changes

2022-08-11 12:56 UTC, merged