[WIP] MESH-1870/ During ticker registration reject ASCII control characters (non printable)
PolymathNetwork/Polymesh pull request #1296
Opened 2022-09-15 02:39 UTC by JMoore96

## changelog

### modified logic

- created a check in ticker registration to make sure it is alphanumeric

2022-09-15 16:48 UTC, Neopallium commented on pallets/asset/src/lib.rs
> +        let result = s.chars().all(char::is_alphanumeric);
This check will reject trailing NULL bytes, which we want to allow.  The alphanumeric check should be done in the look below.

2022-09-15 16:48 UTC, Neopallium commented on pallets/asset/src/lib.rs
>              .position(|b| !matches!(b, 32..=126))
This line should be changed to find the first non-alphanumeric charater.

2022-09-19 19:33 UTC, Neopallium requested changes

2022-09-19 19:33 UTC, Neopallium commented on pallets/asset/src/lib.rs
> +        }
This check will not allow trailing NULL bytes.

This code on line 1206, needs to be changed to use the `is_ascii_alphanumeric` call.
```
.position(|b| !matches!(b, 32..=126))
```

2022-09-20 12:29 UTC, Neopallium commented on pallets/asset/src/lib.rs
> +                !deref_b.is_ascii_alphanumeric()
Parentheses can be used to avoid the local variable.
```suggestion
                !(*b).is_ascii_alphanumeric()
```

2022-09-20 12:39 UTC, Neopallium commented
Looks like some of the reserved classic tickers don't meet the new rules.

2022-09-20 13:50 UTC, Neopallium commented
- [ ] Clear out classic tickers from the `src/data/reserved_classic_tickers.json`.

2022-09-22 15:19 UTC, Neopallium approved these changes

2022-10-05 15:59 UTC, adamdossa approved these changes

2022-10-05 16:15 UTC, merged