[WIP] MESH-1876/ When removing a permissioned operator, each of its associated nodes (stash keys) should be chilled
PolymathNetwork/Polymesh pull request #1317
Opened 2022-09-29 01:19 UTC by JMoore96

## changelog

### modified API

- Added new event for chill_from_governance function

### modified logic

- Added new function chill_from_governance

2022-10-04 12:16 UTC, Neopallium requested changes

2022-10-04 12:16 UTC, Neopallium commented on pallets/staking/src/lib.rs
> +            let _controller = ensure_signed(origin)?;
`ensure_signed` would allow anyone to call this extrinsic.  The staking pallet has 3 types for restricting the `origin`: `RequiredAddOrigin`, `RequiredRemoveOrigin`, and `RequiredCommissionOrigin`.
Here we are forcefully removing an operator, so we want to use the `RequiredRemoveOrigin` restriction:
```suggestion
            T::RequiredRemoveOrigin::ensure_origin(origin)?;
```

2022-10-04 12:16 UTC, Neopallium commented on pallets/staking/src/lib.rs
> +        pub fn chill_from_governance(origin, identity: IdentityId, stash_keys: Vec<T::AccountId>) {
Anytime a `Vec` is a parameter, it's length needs to be used in the weight function and benchmarks.
```suggestion
        #[weight = <T as Config>::WeightInfo::chill_from_governance(stash_keys.len())]
        pub fn chill_from_governance(origin, identity: IdentityId, stash_keys: Vec<T::AccountId>) {
```

2022-10-04 12:16 UTC, Neopallium commented on pallets/staking/src/lib.rs
> +            PermissionedIdentity::remove(&identity);
Need to also check that the identity is a permissioned validator.
```suggestion
            ensure!(Self::permissioned_identity(&identity).is_some(), Error::<T>::NotExists);
            // Change identity status to be Non-Permissioned
            PermissionedIdentity::remove(&identity);
```

2022-10-04 12:16 UTC, Neopallium commented on pallets/staking/src/lib.rs
> +                    if identity == key_did {
The identity check on the stash_keys should be done before the `PermissionedIdentity::remove` call and an error should be thrown, if the keys identity doesn't match `identity`.

2022-10-04 12:16 UTC, Neopallium commented on pallets/staking/src/lib.rs
> +                    if identity == key_did {
Also need to check that each stash_key is a validator: `<Validators<T>>::contains_key(stash_key)`.

2022-10-04 13:18 UTC, Neopallium commented
- [ ] Add unit tests for the new extrinsic.

2022-11-08 11:51 UTC, Neopallium requested changes
Just a little bit of cleanup and this PR is ready.

2022-11-08 11:51 UTC, Neopallium commented on pallets/staking/src/lib.rs
> +        StashNotPartOfDid(AccountId, IdentityId),
This isn't needed anymore.

2022-11-08 11:51 UTC, Neopallium commented on pallets/staking/src/lib.rs
> +        /// And, it can be only called when [`EraElectionStatus`] is `Closed`.
Please update the description to match this new extrinsic.  Also make sure the docs match the standard style that we use listing the parameters and errors.

2022-11-08 11:51 UTC, Neopallium commented on pallets/runtime/tests/src/staking/mod.rs
> +            // Removes 60 and 61 from being validators
```suggestion
            // Removes 50 and 60 from being validators
```

2022-11-10 13:01 UTC, Neopallium approved these changes
Approved, but the description should be improved to describe this new extrinsic.

2022-11-10 13:01 UTC, Neopallium commented on pallets/staking/src/lib.rs
> +        /// Declare no desire to either validate or nominate.
This is the same description as the `chill` extrinsic.  The `chill` extrinsic is for the validator to call themselves, but this new one is for the governance council to force chill a validator.

2022-11-10 18:02 UTC, Neopallium approved these changes

2022-11-14 17:31 UTC, HenriqueNogara approved these changes

2022-11-22 11:17 UTC, adamdossa approved these changes

2022-11-22 11:17 UTC, merged