[WIP] MESH-1879/ If a validator stash is moved between identies then running_count may be incorrect
PolymathNetwork/Polymesh pull request #1333
Opened 2022-10-11 02:13 UTC by JMoore96

## changelog

### modified logic

- made minor changes to running_count insert and delete logic

### data migration required

-  called Identity `add_account_key_ref_count` function on current validators

2022-10-11 12:43 UTC, Neopallium commented
@JMoore96 We will need to merge this PR to fix those compile errors: https://github.com/PolymeshAssociation/Polymesh/pull/1322

2022-11-08 13:55 UTC, Neopallium requested changes
Please add some tests:

1. Ensure that the validator's stash key can't be removed from it's identity.
2. Call `chill` to remove the validator and then ensure that the stash key can be removed from the identity.

2022-11-11 15:32 UTC, Neopallium approved these changes
LGTM

2022-11-14 17:28 UTC, HenriqueNogara approved these changes

2022-11-22 11:37 UTC, adamdossa approved these changes

2022-11-22 11:37 UTC, merged