[WIP] Mesh 1865/asset metadata improvements
PolymathNetwork/Polymesh pull request #1398
Opened 2023-02-06 17:59 UTC by HenriqueNogara

Adds two extrinsics: `remove_local_metadata_key`and `remove_local_metadata_value`.

## changelog

### new features

-  `remove_local_metadata_key` extrinsic;
-  `remove_local_metadata_value` extrinsic;

### modified API

- Adds two error variants: `AssetMetadataKeyBelongsToNFTCollection`, `AssetMetadataValueIsEmpty`
- Adds two events: 

### modified logic

- `base_set_asset_metadata_details` no longer allows locking a key with empty value.

2023-02-07 16:19 UTC, Neopallium requested changes

2023-02-07 16:19 UTC, Neopallium commented on pallets/asset/src/lib.rs
> +        ///
The metadata value can be removed for either local or global keys.

We just can't remove the definition of global keys.

2023-02-07 16:19 UTC, Neopallium commented on pallets/asset/src/lib.rs
> +        }
I think a `match` with all enum variants would be safer here.  If we add a new "Locked" variant in the future, the compiler can help catch it.  Just don't use the catch-all `_ => (),` pattern.

Or just call `detail.lock_status.is_locked(0)`.

2023-02-07 16:19 UTC, Neopallium commented on pallets/common/src/traits/asset.rs
> +        LocalMetadataValueDeleted(Ticker, AssetMetadataName),
These should include the caller's DID as the first parameter.

2023-02-07 16:19 UTC, Neopallium commented on pallets/asset/src/lib.rs
> +        /// Removes a local metadata key.
```suggestion
        /// Removes a local metadata key and value.
```

2023-02-07 16:19 UTC, Neopallium commented on pallets/asset/src/lib.rs
> +        pub fn remove_local_metadata_key(origin, ticker: Ticker, name: AssetMetadataName) -> DispatchResult {
Should use `AssetMetadataLocalKey` instead of the name.

2023-02-28 12:42 UTC, adamdossa approved these changes

2023-02-28 15:43 UTC, Neopallium commented on pallets/asset/src/lib.rs
> +                let _name = AssetMetadataLocalKeyToName::try_get(ticker, &local_key)
Please use `contains_key` here.

2023-03-01 05:35 UTC, Neopallium approved these changes

2023-03-01 05:35 UTC, merged