Delete old migration cold
PolymathNetwork/Polymesh pull request #1401
Opened 2023-02-16 13:12 UTC by HenriqueNogara

Removes old migration code

2023-02-17 16:48 UTC, Neopallium requested changes

2023-02-17 16:48 UTC, Neopallium commented on pallets/multisig/src/lib.rs
> -            }
We need to keep this.  It isn't a migration.  If the TransactionVersion is different, then the Proposals might not be compatible anymore and can't safely be used, so they need to be removed.

2023-02-22 17:16 UTC, Neopallium approved these changes

2023-02-28 12:40 UTC, adamdossa approved these changes

2023-02-28 13:47 UTC, merged