[WIP] Add execute instruction weight
PolymathNetwork/Polymesh pull request #1421
Opened 2023-03-26 21:40 UTC by HenriqueNogara

Add the weight of executing the instruction to `add_with_memo_v2` and `add_and_affirm_instruction_with_memo_v2` 

## changelog

### modified API

- `execute_scheduled_instruction` takes an extra parameter for calculating the weight.

### modified logic

- `execute_scheduled_instruction` now takes the number of nfts transferred to calculate the weight.

2023-03-27 08:58 UTC, adamdossa approved these changes

2023-03-27 11:49 UTC, Neopallium requested changes

2023-03-27 11:49 UTC, Neopallium commented on pallets/settlement/src/lib.rs
> +        fn execute_scheduled_instruction(origin, id: InstructionId, _fungible_transfers: u32, _nfts_transfers: u32) {
We can add the new parameter for 6.0, but not for 5.x.

I recommend moving the code to a `base_exec...` function that take the two counts, then add a new extrinsic that takes both counts, while leaving this one to only take a `leg_count` (just pass it as the fungible count).  This old extrinsic can be renamed `execute_scheduled_instruction_old` and the code below that schedules execution can use the new extrinsic. 

We need to make sure that there isn't any scheduled calls to the old extrinsic before removing/changing it.

2023-03-27 12:02 UTC, Neopallium commented on pallets/weights/src/pallet_settlement.rs
> -    // Storage: Portfolio Portfolios (r:2 w:0)
I wonder why these reads got removed.

2023-03-27 13:51 UTC, Neopallium approved these changes

2023-03-27 14:36 UTC, HenriqueNogara commented on pallets/weights/src/pallet_settlement.rs
> -    // Storage: Portfolio Portfolios (r:2 w:0)
Fixed by not using the default portfolio.

2023-03-27 16:47 UTC, Neopallium commented
Please update the description.

2023-03-28 08:55 UTC, adamdossa approved these changes

2023-03-28 08:55 UTC, merged