Update weights
PolymathNetwork/Polymesh pull request #1458
Opened 2023-05-19 13:18 UTC by adamdossa

If your PR has an external impact, please complete the `changelog` below. Headings under the `changelog` are optional, and should only be included if relevant for this PR.

Please add any general description of the changes before the `changelog`.

Items should be added to the `changelog` using bulletpoints.

## changelog

### new features

- [new feature, schema, events, RPC]

### modified API

- [modified APIs, schema, events, RPC]

### modified logic

- [modified behaviour, bug fixes]

### modified agent functionality

- [the addition or removal of any extrinsics or events emitted by those extrinsics, that relate to permissioned agents]

### data migration

- [storage modified during upgrade process - provide details]

2023-05-19 15:14 UTC, Neopallium requested changes

2023-05-19 15:14 UTC, Neopallium commented on pallets/weights/src/pallet_compliance_manager.rs
> +    fn condition_costs(a: u32, _b: u32, c: u32, _d: u32) -> Weight {
Shouldn't be ignoring `b` here.

2023-05-19 15:14 UTC, Neopallium commented on pallets/weights/src/pallet_compliance_manager.rs
> +    fn change_compliance_requirement(_c: u32) -> Weight {
Shouldn't ignore `c` here.

2023-05-19 15:14 UTC, Neopallium commented on pallets/weights/src/pallet_corporate_actions.rs
> +    fn initiate_corporate_action_use_defaults(w: u32, _t: u32) -> Weight {
Param `t` is important, number of target identities.

2023-05-19 15:14 UTC, Neopallium commented on pallets/weights/src/pallet_identity.rs
> +    fn permissions_cost(_a: u32, _p: u32, l: u32, e: u32) -> Weight {
Can't ignore these parameters.

2023-05-19 15:14 UTC, Neopallium commented on pallets/weights/src/pallet_staking.rs
> -            .saturating_add(DbWeight::get().writes(3))
These reads and writes shouldn't have been removed.

2023-05-19 15:30 UTC, HenriqueNogara approved these changes

2023-05-19 16:08 UTC, HenriqueNogara commented on pallets/weights/src/pallet_compliance_manager.rs
> +    fn condition_costs(a: u32, _b: u32, c: u32, _d: u32) -> Weight {
Is this benchmark being used?

2023-05-22 12:44 UTC, Neopallium approved these changes

2023-05-22 13:36 UTC, merged