Mesh 2045/improve permissions
PolymathNetwork/Polymesh pull request #1464
Opened 2023-06-02 16:46 UTC by HenriqueNogara

This PR adds the `portfolio_kind` parameter to the  `issue` extrinsic and changes `issue` and `controller_transfer` not to require custody checks.

## changelog

### modified API

- Adds a `portfolio_kind` parameter to the `issue` extrinsic;

### modified logic

-  `issue` and `controller_transfer` no longer require custody checks;

2023-06-02 16:47 UTC, HenriqueNogara commented on pallets/common/src/traits/asset.rs
> -pub trait AssetSubTrait {
This was just moved to the end of the file.

2023-06-02 16:49 UTC, HenriqueNogara commented on pallets/asset/src/lib.rs
> -impl<T: Config> AssetFnTrait<T::AccountId, T::RuntimeOrigin> for Module<T> {
Both trait impl were moved to the end of the file. No changes made

2023-06-02 17:21 UTC, Neopallium requested changes
Very minor changes, otherwise looks great.

2023-06-02 17:21 UTC, Neopallium commented on pallets/asset/src/benchmarking.rs
> +    }: _(owner.origin, ticker, (1_000_000 * POLY).into(), PortfolioKind::Default)
Better to use a non-default portfolio in the benchmarks.

2023-06-02 17:21 UTC, Neopallium commented on pallets/nft/src/lib.rs
>          // Ensure origin is agent with custody and permissions for default portfolio.
```suggestion
        // Ensure origin is agent with custody and permissions for portfolio.
```

2023-06-06 19:01 UTC, Neopallium approved these changes

2023-06-12 14:09 UTC, adamdossa approved these changes

2023-06-12 14:09 UTC, merged