Mesh 2090/add nft controller transfer
PolymathNetwork/Polymesh pull request #1529
Opened 2023-09-25 21:19 UTC by HenriqueNogara

## changelog

### new features
- Adds the `controller_transfer` extrinsic to `pallet_nft`;
- Adds `NFTsInCollection` storage to track the number of nfts in a collection;

### modified API
- Adds the following variants to the nft error enum: `SupplyOverflow`, `SupplyUnderflow`; 
- Adds the following event:

2023-09-26 11:02 UTC, Neopallium requested changes
LGTM.  Just a missing migration.

2023-09-26 11:02 UTC, Neopallium commented on pallets/nft/src/lib.rs
> +        pub NFTsInCollection get(fn nfts_in_collection): map hasher(blake2_128_concat) Ticker => NFTCount;
Need a migration for existing NFT collections to initialize this new storage.

2023-09-26 12:27 UTC, Neopallium approved these changes

2023-09-28 15:11 UTC, Neopallium approved these changes

2023-10-17 13:46 UTC, adamdossa approved these changes

2023-10-17 14:10 UTC, merged