MESH-2110/allow-sc-to-create-custodial-portfolios
PolymathNetwork/Polymesh pull request #1547
Opened 2023-10-23 19:48 UTC by HenriqueNogara

Adds extrisincs for allowing a smart contract to create and take custody of user portfolios on behalf of an identity.

## changelog

### new features

- Adds the following extrisincs: `allow_identity_to_create_portfolios`, `revoke_create_portfolios_permission`, `create_custody_portfolio`;

2023-10-25 13:02 UTC, Neopallium requested changes
One minor change need.  Otherwise looks good to me.

2023-10-25 13:02 UTC, Neopallium commented on pallets/portfolio/src/lib.rs
> +        Ok(())
Need to emit the event `PortfolioCustodianChanged`.

2023-10-25 13:33 UTC, Neopallium approved these changes
LGTM

2023-10-26 13:26 UTC, adamdossa approved these changes

2023-10-26 13:26 UTC, merged