WIP: MESH-2096/allow-sc-deploy-as-child-id
PolymathNetwork/Polymesh pull request #1548
Opened 2023-10-26 13:07 UTC by HenriqueNogara

Allows a contract to be deployed as a primary ker of a child identity.

## changelog

### new features

- Adds the following extrisincs: `instantiate_with_code_as_primary_key`;

2023-10-27 17:08 UTC, Neopallium requested changes
Minor extra clones.  Otherwise looks good.

2023-10-27 17:08 UTC, Neopallium commented on pallets/contracts/src/lib.rs
> +        #[weight = Module::<T>::weight_instantiate_with_code(&code, &salt, &Some(perms.clone())).saturating_add(*gas_limit)]
```suggestion
        #[weight = Module::<T>::weight_instantiate_with_code(&code, &salt, Some(&perms)).saturating_add(*gas_limit)]
```
Don't need a `clone` here.  Option can wrap a reference.

2023-10-27 17:08 UTC, Neopallium commented on pallets/contracts/src/lib.rs
> +        perms: &Option<Permissions>,
```suggestion
        perms: Option<&Permissions>,
```

2023-10-27 17:08 UTC, Neopallium commented on pallets/contracts/src/lib.rs
> +    fn weight_instantiate_with_hash(salt: &[u8], perms: &Option<Permissions>) -> Weight {
```suggestion
    fn weight_instantiate_with_hash(salt: &[u8], perms: Option<&Permissions>) -> Weight {
```

2023-10-30 10:36 UTC, Neopallium approved these changes

2023-11-09 12:35 UTC, adamdossa approved these changes

2023-11-09 12:56 UTC, merged