Add validate_ticker_registration_rules, base_create_asset_with_custom…
PolymathNetwork/Polymesh pull request #1591
Opened 2024-02-06 14:49 UTC by HenriqueNogara

## changelog

### new features

[Describe the features being added in the PR]

### modified external API

[List any extrinsics whose behaviour or function signature is modified]

### new external API

[List any new extrinsics being introduced]

### modified events

[List any events whose behaviour, name or arguments is modified]

### new events

[List any new events being introduced]

### other

[List any other relevant information, for example RPC function details]

### data migration

[List any storage modifications required during upgrade process with details]

2024-02-08 16:36 UTC, Neopallium commented on pallets/asset/src/lib.rs
> +        Self::unverified_register_ticker(ticker, caller_did, None)?;
This will always charge the user the "Ticker Registration" protocol fee, even if they pre-registered it.

2024-02-08 16:36 UTC, Neopallium commented on pallets/asset/src/lib.rs
> +        AssetNames::insert(ticker, asset_name.clone());
Done need clone here, can pass by reference.
```suggestion
        AssetNames::insert(ticker, &asset_name);
```

2024-02-08 16:36 UTC, Neopallium commented on pallets/asset/src/lib.rs
> +                CustomTypes::insert(type_id, asset_type_bytes.clone());
Don't need these clones.

2024-02-27 13:07 UTC, Neopallium commented
This PR seems to also include the changes from PR #1603 which is now merged into develop.

2024-02-28 12:04 UTC, Neopallium requested changes

2024-02-28 12:04 UTC, Neopallium commented on pallets/asset/src/lib.rs
> +        let asset_type = AssetType::Custom(custom_asset_type_id);
This is the only code difference between `base_create_asset_with_custom_type` and `base_create_asset`.  These two could be merged by passing `asset_type_bytes` as an optional parameter.

2024-02-28 12:04 UTC, Neopallium commented on pallets/asset/src/lib.rs
> -        Self::ensure_asset_idents_valid(&identifiers)?;
This check is missing, when an asset is created.

2024-02-28 14:32 UTC, Neopallium approved these changes

2024-02-28 16:50 UTC, Neopallium approved these changes

2024-03-08 14:30 UTC, adamdossa approved these changes

2024-03-08 14:33 UTC, merged