Mesh 1992/add-max-auths
PolymathNetwork/Polymesh pull request #1649
Opened 2024-04-11 13:08 UTC by HenriqueNogara

## changelog

### new features

### new external API

- Adds the following error variant to the identity pallet: `ExceededNumberOfGivenAuths`;
- Adds the following storage tot the identity pallet: `NumberOfGivenAuths`,`OutdatedAuthorizations`, `CurrentAuthId`;

### other

- `add_auth` returns an error if  `MaxGivenAuths` is exceeded;
- `ensure_authorization` also check if the authorizations is oudated;
- `remove_secondary_keys` also set authorizations as outdated;
- `unsafe_add_auth_for_signers` returns an error if `MaxGivenAuths` is exceeded;
- `unverified_add_auth_for_paying_key` returns an error if `MaxGivenAuths` is exceeded;

### data migration

 - Initializes `CurrentAuthId`;
 - Initializes `NumberOfGivenAuths`;

2024-04-16 14:22 UTC, Neopallium requested changes
Just one small change needed, otherwise looks good.

2024-04-16 14:22 UTC, Neopallium commented on pallets/identity/src/auth.rs
> +        });
There are a few more places where an authorization is removed and we will need to decrease the `NumberOfGivenAuths`.

2024-04-16 16:24 UTC, Neopallium approved these changes

2024-05-08 11:56 UTC, adamdossa approved these changes

2024-05-08 11:56 UTC, merged