Mesh 2176/fix-storage-naming
PolymathNetwork/Polymesh pull request #1658
Opened 2024-04-24 12:00 UTC by HenriqueNogara

## changelog

### modified external API

- Deprecate the following asset storage: `AssetMetadataNextLocalKey`,  `AssetMetadataNextGlobalKey`;
- Deprecate the following NFT storage: `NextCollectionId`, `NextNFTId`;

### new external API

- Add the following asset storage: `CurrentAssetMetadataLocalKey`, `CurrentAssetMetadataGlobalKey`;
- Add the following NFT storage: `CurrentNFTId`, `CurrentCollectionId`;

### data migration
- Initializes new storage for the asset pallet;
- Initializes new storage for the nft pallet;

2024-04-29 16:10 UTC, Neopallium requested changes

2024-04-29 16:10 UTC, Neopallium commented on pallets/asset/src/lib.rs
> +        AssetMetadataNextGlobalKey::try_mutate(try_next_pre::<T, _>)?;
Just set the old storage value to `key`.  The mutate operation has an extra read that we don't need.

2024-04-29 16:10 UTC, Neopallium commented on pallets/asset/src/lib.rs
> +        AssetMetadataNextLocalKey::try_mutate(ticker, try_next_pre::<T, _>)?;
Same here.  Just set the old storage value to the same value `key`.

2024-04-29 16:10 UTC, Neopallium commented on pallets/asset/src/lib.rs
> +    use crate::sp_api_hidden_includes_decl_storage::hidden_include::StorageValue;
Please don't import these from a "hidden" crate, they should be available from a public crate.

2024-04-29 16:10 UTC, Neopallium commented on pallets/nft/src/lib.rs
> +        NextCollectionId::try_mutate(try_next_pre::<T, _>)?;
Use set instead of mutate for the old storage.

2024-04-29 16:10 UTC, Neopallium commented on pallets/nft/src/lib.rs
> +        NextNFTId::try_mutate(&collection_id, try_next_pre::<T, _>)?;
Same here.

2024-04-29 16:10 UTC, Neopallium commented on pallets/nft/src/lib.rs
> +    use crate::sp_api_hidden_includes_decl_storage::hidden_include::StorageValue;
Same here.  Don't use hidden imports.

2024-04-30 13:36 UTC, Neopallium approved these changes

2024-05-07 12:56 UTC, adamdossa approved these changes

2024-05-07 13:53 UTC, merged