Mesh 2188/migrations
PolymathNetwork/Polymesh pull request #1699
Opened 2024-08-08 12:38 UTC by HenriqueNogara

## changelog

### data migration

* pallet_checkpoint
     * __The following storage have been migrated:__ TotalSupply, Balance, CheckpointIdSequence, BalanceUpdates, Timestamps, ScheduleIdSequence, CachedNextCheckpoints, ScheduledCheckpoints, ScheduleRefCount, SchedulePoints;
     
* pallet_compliance_manager
     *  __The following storage been migrated:__ AssetCompliances, TrustedClaimIssuer;
     
* pallet_ballot
     *  __The following storage been migrated:__ Metas, TimeRanges, MotionNumChoices, RCV, Results, Votes;

* pallet_distribution
     *  __The following storage been migrated:__ Distributions, HolderPaid;
    
* pallet_asset
     * __The following storage have been migrated:__ Tickers, Tokens, Identifiers, TickersExemptFromAffirmation, AssetNames, BalanceOf, FundingRound, IssuedInFundingRound, Frozen, AssetDocuments, AssetDocumentsIdSequence, AssetMetadataValues, AssetMetadataValueDetails, AssetMetadataLocalNameToKey, AssetMetadataLocalKeyToName, AssetMetadataLocalSpecs, AssetMetadataNextLocalKey, MandatoryMediators, CurrentAssetMetadataLocalKey; 

* pallet_corporate_actions
     *  __The following storage have been migrated:__ DefaultTargetIdentities, DefaultWithholdingTax, DidWithholdingTax, CAIdSequence, CorporateActions;
 
* pallet_external_agents
     *  __The following storage have been migrated:__ AGIdSequence, AgentOf, GroupOfAgent, NumFullAgents, GroupPermissions; 
     
* pallet_nft
     *  __The following storage have been migrated:__ NumberOfNFTs, CollectionTicker, Collection, NFTsInCollection, NFTOwner;

*  pallet_portfolio
     *  __The following storage have been migrated:__ PortfolioAssetBalances, PortfolioLockedAssets, PortfolioNFT, PortfolioLockedNFT, PreApprovedPortfolios;
    
*  pallet_settlement
     *  __The following storage have been migrated:__ VenueFiltering, VenueAllowList, InstructionLegs;
     
*  pallet_statistics
     *  __The following storage have been migrated:__ ActiveAssetStats, AssetTransferCompliances, AssetStats, TransferConditionExemptEntities;
     
*  pallet_sto
     *  __The following storage have been migrated:__ Fundraisers, FundraiserCount, FundraiserNames;

2024-08-12 14:56 UTC, Neopallium requested changes

2024-08-12 14:56 UTC, Neopallium commented on pallets/asset/src/checkpoint/migrations.rs
> +    log::info!("Updating types for the Balance storage");
I recommend counting how many items are migrated and printing the count.  The nodes will log this information and we can use it to double check that the correct number of items have been migrated.

2024-08-12 14:56 UTC, Neopallium commented on pallets/asset/src/migrations.rs
> +    v4::FundingRound::drain().for_each(|(ticker, name)| {
Missing migration for `Identifiers` storage.

2024-08-13 11:34 UTC, Neopallium approved these changes

2024-08-14 14:30 UTC, adamdossa approved these changes

2024-08-14 14:30 UTC, merged