Run all benchmarks
PolymathNetwork/Polymesh pull request #1705
Opened 2024-08-21 18:04 UTC by HenriqueNogara

## changelog

### other
* Update weights for all pallets;

2024-08-23 14:19 UTC, Neopallium requested changes

2024-08-23 14:19 UTC, Neopallium commented on pallets/weights/src/pallet_asset.rs
> +        Weight::from_ref_time(38_142_950)
Ignored param.

2024-08-23 14:19 UTC, Neopallium commented on pallets/weights/src/pallet_compliance_manager.rs
> +    fn condition_costs(a: u32, b: u32, c: u32, _d: u32) -> Weight {
Ignored param.

2024-08-23 14:19 UTC, Neopallium commented on pallets/weights/src/pallet_identity.rs
> +    fn permissions_cost(_a: u32, _p: u32, l: u32, e: u32) -> Weight {
Two ignored params.

2024-08-23 14:19 UTC, Neopallium commented on pallets/weights/src/pallet_statistics.rs
> +    fn active_asset_statistics_load(_a: u32) -> Weight {
Ignored param.

2024-08-23 14:19 UTC, Neopallium commented on pallets/weights/src/polymesh_contracts.rs
> +    fn basic_runtime_call(_n: u32) -> Weight {
Ignored param.

2024-08-23 14:19 UTC, Neopallium commented on pallets/weights/src/polymesh_contracts.rs
> +    fn basic_runtime_call(_n: u32) -> Weight {
This is fine.

2024-08-23 14:19 UTC, Neopallium commented on pallets/weights/src/pallet_asset.rs
> +        Weight::from_ref_time(38_142_950)
Might have to increase the MaxAssetMediators limit for the benchmarks.

2024-08-23 14:19 UTC, Neopallium commented on pallets/weights/src/pallet_compliance_manager.rs
> +    fn condition_costs(a: u32, b: u32, c: u32, _d: u32) -> Weight {
We can manually add it again like last time.

2024-08-23 14:19 UTC, Neopallium commented on pallets/weights/src/pallet_identity.rs
> +    fn permissions_cost(_a: u32, _p: u32, l: u32, e: u32) -> Weight {
Same here.  They were manually added last time, so we should do the same for now.

2024-08-23 14:19 UTC, Neopallium commented on pallets/weights/src/pallet_statistics.rs
> +    fn active_asset_statistics_load(_a: u32) -> Weight {
We only have one call to this can it uses the max stats per asset limit for the `a` parameter.  Maybe the benchmarks should run with the same value instead of a range?

2024-08-23 14:19 UTC, Neopallium commented on pallets/weights/src/pallet_contracts.rs
> +            .saturating_add(DbWeight::get().writes((800_u64).saturating_mul(r.into())))
This increase is normal.  The batch size is 80 and we added 3 more writes: `3 * 80 = 240`, `560 + 240 = 800`.

2024-08-23 14:20 UTC, Neopallium commented on pallets/weights/src/pallet_asset.rs
> +        Weight::from_ref_time(38_142_950)
For now just manually copy old weight for the `n` param.  We should create a ticket for this benchmark.

2024-08-27 13:16 UTC, Neopallium approved these changes

2024-08-29 12:08 UTC, adamdossa approved these changes

2024-08-29 12:09 UTC, merged