[WIP] Fix v7 migrations
PolymathNetwork/Polymesh pull request #1709
Opened 2024-08-29 10:23 UTC by Neopallium

Fix v7 migrations when the map/double map keys change type.

2024-08-30 17:51 UTC, HenriqueNogara requested changes

2024-08-30 17:51 UTC, HenriqueNogara commented on pallets/portfolio/src/migrations.rs
> +    move_prefix(
```Rust
move_prefix(
   &PreApprovedPortfolios::final_prefix(),
   &v2::OldPreApprovedPortfolios::final_prefix(),
);

2024-09-02 16:55 UTC, HenriqueNogara approved these changes

2024-09-10 11:53 UTC, adamdossa approved these changes

2024-09-10 11:53 UTC, merged