Small fixes
PolymathNetwork/Polymesh pull request #1739
Opened 2024-10-15 12:24 UTC by HenriqueNogara

## changelog

### modified external API
- Removes deprecated extrinsics from the utility pallet: `batch_old`, `batch_atomic`, `batch_optimistic`;
- Adds `SelfAdditionNotAllowed` restriction in the `allow_identity_to_create_portfolios` extrinsic;
### modified events
- Removes the following events from the utility pallet: `BatchInterruptedOld`, `BatchOptimisticFailed`, `BatchCompletedOld`;
### other
- Improve weight calculation in the utility pallet; 
- Improve weight calculation in the `create_portfolio` extrinsic;

2024-10-15 13:03 UTC, adamdossa approved these changes

2024-10-15 15:15 UTC, Neopallium requested changes
Only one small change needed.  Otherwise looks good.

2024-10-15 15:15 UTC, Neopallium commented on pallets/utility/src/lib.rs
> +        #[pallet::call_index(6)]
We should leave the extrinsic call_index values fixed.  Any change to these will require a change to the `transaction_version` and update to the Ledger app.

2024-10-16 12:39 UTC, Neopallium approved these changes

2024-10-16 12:39 UTC, merged