Update pallet to use new macros
PolymathNetwork/Polymesh pull request #1753
Opened 2024-11-15 18:29 UTC by HenriqueNogara

## changelog

### other
- Update pallet to use new macros;

2024-11-19 13:29 UTC, Neopallium requested changes
Only a minor issue with missing pallet constants.  Otherwise looks good.

2024-11-19 13:29 UTC, Neopallium commented on pallets/transaction-payment/src/lib.rs
> -            T::WeightToFee::polynomial().to_vec();
Need to export `#[pallet::constant]` these two constants in the `Config` trait.

2024-11-26 14:52 UTC, Neopallium approved these changes

2024-11-26 16:19 UTC, adamdossa approved these changes

2024-11-27 15:08 UTC, Neopallium approved these changes

2024-11-27 15:08 UTC, merged