WIP: Update PIPs pallet
PolymathNetwork/Polymesh pull request #1777
Opened 2024-12-30 21:51 UTC by HenriqueNogara

## changelog

### other

### data migration

2024-12-31 11:44 UTC, Neopallium requested changes
Looks good.  Just a few minor things.

2024-12-31 11:44 UTC, Neopallium commented on pallets/pips/src/lib.rs
> +        MaxPipSkipCountChanged(IdentityId, u8, u8),
Lets keep that type alias.

2024-12-31 11:44 UTC, Neopallium commented on pallets/pips/src/lib.rs
> +    }
It should be possible to use `#[derive(frame_support::DefaultNoBound)]` to avoid having to manually impl `Default`.

2024-12-31 11:44 UTC, Neopallium commented on pallets/pips/src/lib.rs
> +        // Prune the PIP given by the `id`, refunding any funds not already refunded.
I think this change was a mistake?

2024-12-31 11:44 UTC, Neopallium commented on pallets/pips/src/lib.rs
> -    fn compare_spip_works() {
We should keep this test, it can be moved into the `types.rs` file.

2024-12-31 11:44 UTC, Neopallium commented on pallets/pips/src/lib.rs
> -    fn compare_spip_works() {
The other tests here are not needed anymore.

2024-12-31 14:14 UTC, Neopallium approved these changes

2025-01-16 12:27 UTC, adamdossa approved these changes

2025-01-16 16:40 UTC, merged