Rename Authorize to affirm
PolymathNetwork/Polymesh pull request #676
Opened 2020-10-15 06:47 UTC by satyamakgec

2020-10-15 07:03 UTC, maxsam4 commented on pallets/settlement/src/lib.rs
> +        /// * `portfolios` - Portfolios that the sender controls and wants to affirm this instruction
This doesn't sound right. Maybe try something like
```suggestion
        /// * `portfolios` - Portfolios that the sender controls and wants to use in this affirmation
```

2020-10-15 07:03 UTC, maxsam4 commented on pallets/settlement/src/lib.rs
> +            let user_auth = Self::user_affirms(portfolio, instruction_id);
```suggestion
            let user_affirmation = Self::user_affirms(portfolio, instruction_id);
```

2020-10-16 11:31 UTC, adamdossa approved these changes

2020-10-16 12:36 UTC, maxsam4 requested changes

2020-10-16 12:36 UTC, maxsam4 commented on pallets/settlement/src/lib.rs
> +//! - `withdraw_instruction` - Deny an existing instruction.
`withdraw_instruction` is not correct. The function withdraws the `affirmation`, not the instruction.

2020-10-16 12:36 UTC, maxsam4 commented on pallets/settlement/src/lib.rs
> +        InstructionDenied(IdentityId, PortfolioId, u64),
`InstructionDenied` -> `AffirmationWithdrawn`

2020-10-16 14:09 UTC, maxsam4 approved these changes

2020-10-16 14:49 UTC, merged