MESH-1433: Introduce limits for fixed values in CA extrinsic weights
PolymathNetwork/Polymesh pull request #827
Opened 2020-12-28 19:49 UTC by Centril

## changelog

### modified logic

- [modified behaviour, bug fixes]

2020-12-29 08:39 UTC, fmiguelgarcia requested changes

2020-12-29 08:39 UTC, fmiguelgarcia commented on pallets/corporate-actions/src/lib.rs
> +            targets.identities.len().try_into().unwrap_or(u32::MAX) <= T::MaxTargetIds::get(),
```suggestion
            targets.identities.len() <= T::MaxTargetIds::get() as usize,
```

2020-12-29 08:39 UTC, fmiguelgarcia commented on pallets/corporate-actions/src/lib.rs
> +            len.try_into().unwrap_or(u32::MAX) <= T::MaxDidWhts::get(),
```suggestion
            len <= T::MaxDidWhts::get() as usize,
```

2020-12-29 11:04 UTC, fmiguelgarcia approved these changes

2020-12-31 07:27 UTC, maxsam4 approved these changes

2020-12-31 08:27 UTC, merged