MESH-1556: allow distribution past dividend date
PolymathNetwork/Polymesh pull request #926
Opened 2021-02-23 15:15 UTC by vkomenda

## changelog

### modified API

- The error `NowAfterPayment` is no longer emitted by the `distribute` extrinsic of the `CapitalDistribution` pallet.

### modified logic

- The `distribute` extrinsic of the `CapitalDistribution` pallet can now be called past the dividend date defined in the `payment_at` argument.

2021-02-23 15:26 UTC, Centril requested changes

2021-02-23 15:26 UTC, Centril commented on pallets/runtime/tests/src/corporate_actions_test.rs
> -        );
Let's make this into an `assert_ok!` test instead.

2021-02-23 18:52 UTC, Centril approved these changes

2021-02-24 08:20 UTC, satyamakgec approved these changes

2021-02-24 10:59 UTC, maxsam4 approved these changes

2021-02-24 11:00 UTC, merged