[WIP] MESH-1408/Refactor canTransfer to return all Results
PolymathNetwork/Polymesh pull request #928
Opened 2021-02-24 09:14 UTC by CJP10

## changelog

### new features

- new asset rpc `can_transfer_granular`

2021-02-26 07:06 UTC, maxsam4 requested changes

2021-02-26 07:06 UTC, maxsam4 commented on primitives/src/asset.rs
> +    pub compliance_failure: bool,
We need these to be more granular. See the can transfer in compliance pallet. Result of that call should be included here basically.

2021-02-26 07:06 UTC, maxsam4 commented on primitives/src/asset.rs
> +    pub statistics_failure: bool,
We need these to be more granular. i.e. It should list all transfer managers in statistics module and if they passed/failed.

2021-03-03 13:30 UTC, vkomenda commented on pallets/statistics/src/lib.rs
> +                },
Matching on `&tm` first should allow to remove cloning from `tm`.

2021-03-03 13:53 UTC, Centril commented on pallets/asset/src/lib.rs
> +        if Self::missing_scope_claim(ticker, to_portfolio.did, from_portfolio.did) {
Function is always called with `portfolio.did`, so let's take the portfolio ids instead

2021-03-03 13:53 UTC, Centril commented on pallets/runtime/common/src/runtime.rs
> +                    value: Balance) -> polymesh_primitives::asset::GranularCanTransferResult
```suggestion
                    value: Balance
                ) -> polymesh_primitives::asset::GranularCanTransferResult
```

2021-03-03 13:53 UTC, Centril commented on primitives/src/asset.rs
> +/// Result of a granular can transfer
Nit: add punctuation in doc comments.

2021-03-03 17:53 UTC, fmiguelgarcia approved these changes

2021-03-03 17:53 UTC, fmiguelgarcia commented on rpc/runtime-api/src/asset.rs
> +         /// TODO
TODO??

2021-03-05 06:51 UTC, CJP10 commented on pallets/asset/src/lib.rs
> +    }
From my understanding `#[inline]`  It only useful when not use LTO and inlining fns across crates. In this case, all these 1 liners are private and  `#[inline]` would have no impact.

2021-03-08 04:40 UTC, maxsam4 commented
@CJP10 The schema needs to be updated.

2021-03-09 05:44 UTC, maxsam4 approved these changes

2021-03-09 10:40 UTC, merged