UT for `add_investor_uniqueness_claim_v2`
PolymathNetwork/Polymesh pull request #970
Opened 2021-03-22 17:56 UTC by fmiguelgarcia

TODO

## changelog

### new features

- [new feature, schema, events, RPC]

### modified API

- [modified APIs, schema, events, RPC]

### modified logic

- [modified behaviour, bug fixes]

2021-03-23 10:03 UTC, satyamakgec approved these changes

2021-03-24 05:10 UTC, maxsam4 requested changes

2021-03-24 05:10 UTC, maxsam4 commented on primitives/src/valid_proof_of_investor/v2.rs
> +        if proof_scope_id == scope_id.as_bytes() {
@fmiguelgarcia I'm still not seeing why we need `scope_id` in the claim when we can just get it from `proof.0.scope_id`.

We can have a new claim variant, `Claim::InvestorUniquenessv2` or something like that that does not have `scope_id`.

2021-03-24 05:10 UTC, maxsam4 commented on primitives/src/valid_proof_of_investor/v2.rs
> +        let scope_did = slice_to_scalar(scope);
Let's not use "scope_did" anywhere. We can call this `scope` or `scope_scalar`

2021-03-24 18:13 UTC, maxsam4 commented on pallets/identity/src/lib.rs
> +            Claim::InvestorUniquenessV2(scope, _) => match scope {
Do we even need `scope` in this claim since we already have `scope` in `sk`?

2021-03-29 17:50 UTC, vkomenda commented on pallets/identity/src/lib.rs
> +        /// Revokes a specific claim using its claim unique index, instead of its
Please rephrase the description in terms of `target`, `claim_type` and `scope`.

2021-03-29 17:50 UTC, vkomenda commented on pallets/identity/src/lib.rs
> +        /// Please note that only the `issuer` of the target claim can effectively call this function, because its `DID` is part of claim index.
There is no `issuer` among the arguments. To find it you would need to go to the source code.
`DID` is not an identifier so it shouldn't be monospaced.

2021-04-06 09:34 UTC, maxsam4 approved these changes

2021-04-06 09:35 UTC, merged