MESH-1597/
PolymathNetwork/Polymesh pull request #981
Opened 2021-04-07 04:48 UTC by CJP10

If your PR has an external impact, please complete the `changelog` below. Headings under the `changelog` are optional, and should only be included if relevant for this PR.

Please add any general description of the changes before the `changelog`.

Items should be added to the `changelog` using bulletpoints.

## changelog

### new features

- `Asset::create_asset_and_mint` does what `Asset::create_asset` used to do

### modified API

- `Asset::create_asset` no longer mints tokens be default

2021-04-08 09:12 UTC, Centril requested changes

2021-04-08 09:12 UTC, Centril commented on pallets/asset/src/lib.rs
> -        );
Looks like you're removing a bunch of checks in general from asset creation.
Also, the checks relevant to `total_supply` need to be moved to the `_and_mint` variant.

2021-04-08 10:46 UTC, fmiguelgarcia reviewed
Minor comments

2021-04-08 10:46 UTC, fmiguelgarcia commented on pallets/asset/src/lib.rs
> +        /// * `total_supply` - the total supply of the token.
doc error

2021-04-08 10:46 UTC, fmiguelgarcia commented on pallets/asset/src/lib.rs
> +        /// - `TotalSupplyAboveLimit` if `total_supply > MAX_SUPPLY`.
doc error

2021-04-09 08:09 UTC, Centril commented on pallets/asset/src/lib.rs
> +        /// without minting the tokens. Use `issue` to mint the tokens.
```suggestion
        /// Initializes a new security token, with the initiating account as its owner.
        /// The total supply will initially be zero. To mint tokens, use `issue`.
```

2021-04-09 08:12 UTC, Centril commented
```
test_1            | Error: Extrinsic asset.createAsset expects 6 arguments, got 7.
test_1            |     at assert (/clicode/scripts/cli/node_modules/@polkadot/util/assert.js:34:11)
test_1            |     at extrinsicFn (/clicode/scripts/cli/node_modules/@polkadot/metadata/decorate/extrinsics/createUnchecked.js:23:22)
test_1            |     at Object.decorated [as createAsset] (/clicode/scripts/cli/node_modules/@polkadot/api/base/Decorate.js:346:46)
test_1            |     at Object.issueTokenPerDid (/clicode/scripts/cli/util/init.js:302:38)
test_1            |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
test_1            |     at async main (/clicode/scripts/cli/tests/4_permission_management.js:30:3)
```

Integration test needs to be fixed and I think this should be good to go.

2021-04-12 04:47 UTC, maxsam4 commented on pallets/asset/src/lib.rs
> +        pub fn create_asset_and_mint(
This is not needed, let's remove it. Users can batch call `create_asset` and `issue` to get this functionality.

2021-04-12 11:35 UTC, fmiguelgarcia approved these changes

2021-04-14 12:39 UTC, Centril approved these changes

2021-04-15 10:13 UTC, maxsam4 commented on pallets/asset/src/lib.rs
> +    #[inline]
I don't think this should be inlined

2021-04-15 10:13 UTC, maxsam4 approved these changes

2021-04-15 13:32 UTC, merged