MESH-1598/ use expect/assert in benchmarks
PolymathNetwork/Polymesh pull request #986
Opened 2021-04-08 21:58 UTC by JMoore96

Changed all `?` operators in the benchmarks to `unwrap()` and changed all `ensure`'s to `assert`.

2021-04-09 18:37 UTC, Centril requested changes
These comments outline the general principle... but there are more instances of this in the code.
Please adjust the remaining ones as well.

2021-04-09 18:37 UTC, Centril commented on pallets/common/src/benchs/asset.rs
> +    .unwrap();
```suggestion
    .unwrap();
```

2021-04-09 18:37 UTC, Centril commented on pallets/compliance-manager/src/benchmarking.rs
> +        assert!( req.receiver_conditions == d.receiver_conditions, "Sender conditions not expected");
```suggestion
        assert_eq!(req.sender_conditions, d.sender_conditions, "Sender conditions not expected");
        assert_eq!(req.receiver_conditions, d.receiver_conditions, "Sender conditions not expected");
```

2021-04-09 18:37 UTC, Centril commented on pallets/compliance-manager/src/benchmarking.rs
> +        assert!( Module::<T>::asset_compliance(d.ticker).paused == true, "Asset compliance is not paused");
```suggestion
        assert!(Module::<T>::asset_compliance(d.ticker).paused, "Asset compliance is not paused");
```

2021-04-09 18:37 UTC, Centril commented on pallets/compliance-manager/src/benchmarking.rs
> +        assert!( Module::<T>::asset_compliance(d.ticker).paused == false, "Asset compliance is paused");
```suggestion
        assert!(!Module::<T>::asset_compliance(d.ticker).paused, "Asset compliance is paused");
```

2021-04-09 18:37 UTC, Centril commented on pallets/compliance-manager/src/benchmarking.rs
> +        assert!( req == new_req,
```suggestion
        assert_eq!(req, new_req,
```

2021-04-09 18:37 UTC, Centril commented on pallets/compliance-manager/src/benchmarking.rs
> +        assert!( reqs == asset_compliance, "Asset compliance was not replaced");
```suggestion
        assert_eq!(reqs, asset_compliance, "Asset compliance was not replaced");
```

2021-04-09 18:37 UTC, Centril commented on pallets/contracts/src/benchmarking.rs
> +        assert!(Module::<T>::get_template_details(code_hash).get_instantiation_fee() == 500u32.into(), "Contracts_change_template_fees: Failed to change the instantiation fees");
```suggestion
        assert_eq!(Module::<T>::get_template_details(code_hash).get_instantiation_fee(), 500u32.into(), "Contracts_change_template_fees: Failed to change the instantiation fees");
```

2021-04-09 18:37 UTC, Centril commented on pallets/contracts/src/benchmarking.rs
> +        assert!(Module::<T>::get_metadata_of(code_hash).usage_fee == 650u32.into(), "Contracts_change_template_fees: Failed to change the usage fees");
```suggestion
        assert_eq!(Module::<T>::get_metadata_of(code_hash).usage_fee, 650u32.into(), "Contracts_change_template_fees: Failed to change the usage fees");
```

2021-04-09 18:37 UTC, Centril commented on pallets/contracts/src/benchmarking.rs
> +        assert!(Module::<T>::get_metadata_of(code_hash).url == url, "Contracts_change_template_meta_url: Failed to change the url of template");
```suggestion
        assert_eq!(Module::<T>::get_metadata_of(code_hash).url, url, "Contracts_change_template_meta_url: Failed to change the url of template");
```

2021-04-09 18:37 UTC, Centril commented on pallets/contracts/src/benchmarking.rs
> +        assert!(Module::<T>::is_put_code_enabled() == false, "Contracts_set_put_code_flag: Unexpected initial state");
```suggestion
        assert!(!Module::<T>::is_put_code_enabled(), "Contracts_set_put_code_flag: Unexpected initial state");
```

2021-04-09 18:37 UTC, Centril commented on pallets/contracts/src/benchmarking.rs
> +        assert!(Module::<T>::is_put_code_enabled() == true, "Contracts_set_put_code_flag: Failed to change the flag");
```suggestion
        assert!(Module::<T>::is_put_code_enabled(), "Contracts_set_put_code_flag: Failed to change the flag");
```

2021-04-09 18:37 UTC, Centril commented on pallets/corporate-actions/src/ballot/benchmarking.rs
> +        assert!(TimeRanges::get(ca_id) == Some(RANGE), "ballot not created");
```suggestion
        assert_eq!(TimeRanges::get(ca_id), Some(RANGE), "ballot not created");
```

2021-04-09 18:37 UTC, Centril commented on pallets/corporate-actions/src/ballot/benchmarking.rs
> +        assert!(<Results<T>>::get(ca_id) == results, "voting results are wrong")
```suggestion
        assert_eq!(<Results<T>>::get(ca_id), results, "voting results are wrong")
```

2021-04-12 11:31 UTC, fmiguelgarcia approved these changes

2021-04-14 22:24 UTC, CJP10 approved these changes

2021-04-14 22:24 UTC, CJP10 commented on pallets/asset/src/checkpoint/benchmarking.rs
> +        // assert it will fit in the max complexity.
```suggestion
        // Must fit in the max complexity.
```

2021-04-22 11:01 UTC, Centril commented on pallets/common/src/benchs/asset.rs
> +    .unwrap();
```suggestion
    .expect("Asset cannot be created");
```

2021-04-22 11:01 UTC, Centril commented on pallets/common/src/benchs/asset.rs
> +        .unwrap();
```suggestion
        .expect("Ticker cannot be registered");
```

2021-04-22 11:01 UTC, Centril commented on pallets/common/src/benchs/asset.rs
> +            .unwrap(),
```suggestion
            .expect("Invalid ticker name"),
```

2021-04-26 13:19 UTC, JMoore96 commented on pallets/sto/src/benchmarking.rs
> +        assert!(<Fundraisers<T>>::get(OFFERING_TICKER, 0).unwrap().status == FundraiserStatus::Frozen, "freeze_fundraiser");
For this change I got an error saying  `FundraiserStatus` cannot be formatted using `{:?}`, `assert_eq!(<Fundraisers<T>>::get(OFFERING_TICKER, 0).unwrap().status, FundraiserStatus::Frozen, "freeze_fundraiser");`

2021-04-26 13:25 UTC, JMoore96 commented on pallets/settlement/src/benchmarking.rs
> +        assert!(matches!(updated_venue_details.details, venue_details), "Incorrect venue details");
I got an error stating the ventue_details is 'value borrowed here after move' as in line 553 it is used in Some(venue_details)

2021-04-26 13:29 UTC, JMoore96 commented on pallets/pips/src/benchmarking.rs
> +        assert!(state == Module::<T>::proposals(&0).unwrap().state, err);
When implementing this it gave the message 'error: format argument must be a string literal' for the err variable and suggested  `assert_eq!(state, Module::<T>::proposals(&0).unwrap().state, "{}", err);`

2021-04-27 06:49 UTC, Centril commented on pallets/sto/src/benchmarking.rs
> +        assert!(<Fundraisers<T>>::get(OFFERING_TICKER, 0).unwrap().status == FundraiserStatus::Frozen, "freeze_fundraiser");
To fix this, take the `#[cfg_attr(feature = "std", derive(Debug))]` on `FundraiserStatus` and replace it with `#[derive(Debug)]`.

2021-04-27 06:50 UTC, Centril commented on pallets/pips/src/benchmarking.rs
> +        assert!(state == Module::<T>::proposals(&0).unwrap().state, err);
Yep, use that suggestion.

2021-04-27 06:55 UTC, Centril commented on pallets/settlement/src/benchmarking.rs
> +        assert!(matches!(updated_venue_details.details, venue_details), "Incorrect venue details");
Do `let venue_details2 = venue_details.clone();` right after `let venue_details = ...;` and then use `venue_details2` here.

2021-04-28 12:38 UTC, maxsam4 approved these changes

2021-04-28 12:43 UTC, Centril approved these changes

2021-05-03 06:53 UTC, merged